export const STATUS = {
  ERROR: 'ERROR',
  LOADING: 'LOADING',
  NOT_STARTED: 'NOT_STARTED',
  SUCCESS: 'SUCCESS'
}

export const BUILD_VARIANT = {
  DEV: 'DEV',
  STAGING: 'STAGING',
  PROD: 'PROD'
}

export const FILTER_OPTIONS = {
  DROPDOWN: 'DROPDOWN',
  DATE_PICKER: 'DATE_PICKER',
  DROPDOWN_SEARCH: 'DROPDOWN_SEARCH',
  TEXT_INPUT: 'TEXT_INPUT'
}
